config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get   'tasks',          to: 'tasks#index'
  post  'tasks',          to: 'tasks#create'
  get   'tasks/new',      to: 'tasks#new'
  get   'tasks/:id',      to: 'tasks#show', as: :task
  get   'tasks/:id/edit', to: 'tasks#edit', as: :tasks_edit
  patch 'tasks/:id',      to: 'tasks#update'
  delete 'tasks/:id',     to: 'tasks#destroy', as: :tasks_destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def edit
  end

  def update
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= label_tag :completed, "Completed ?" %>
  <%= f.check_box :completed %>
  <%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<h1>The ugly TO DO manager 💩</h1>

<h3>Edit here your task :</h3>

<%= render 'form', task: @task %>

app/views/tasks/index.html.erb
<div class="main-container">
  <h1>The ugly TO DO manager 💩</h1>

  <h3>⬇️ Here's your boring list 🤓 ⬇️</h3>

  <div class="tasks"><% @tasks.each do |t| %>
    <p class="task"> 〰️
      <%= t.completed ? "✅" : "🟥" %>
      <%= link_to "#{t.title}", task_path(t) %>
      <%= link_to "❌", task_path(t), method: :delete, data: { confirm: "Are you sure?" } %>
      </p>
    <% end %>
  </div>

  <p><%= link_to "➕ CREATE A NEW TASK", tasks_new_path %></p>

  <h3>👹 Hurry up ! 💀</h3>
</div>

app/views/tasks/new.html.erb
<h1>The ugly TO DO manager 💩</h1>

<h3>Create here your new task :</h3>

<%= render 'form', task: @task %>

app/views/tasks/show.html.erb
<h1>The ugly TO DO manager 💩</h1>

<h2><%=@task.title%></h2>

<p><%=@task.details%></p>

<p><%= link_to "🔁 Edit the task", tasks_edit_path(@task.id) %></p>

<div class="link">
  <%= link_to "➤ Back to the list", tasks_path %>
</div>